name: Detect Repository Languages
description: Detects if specified languages are present in the repository and outputs flags for each.
outputs:
  should-run-codeql:
    description: 'Flag indicating if CodeQL scan should be run.'
  should-run-trivy:
    description: 'Flag indicating if Trivy scan should be run.'
  should-run-horusec:
    description: 'Flag indicating if Horusec scan should be run.'
runs:
  using: 'node20'
  main: 'index.js'