name: Language-Based SATS Scan

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read  # Required for checking code and triggering events
  actions: write  # Required for triggering workflows with repository_dispatch

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect Repository Languages
        id: detect
        uses: ./.github/actions/detect-languages
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug Detected scan flags
        run: |
          echo "Should run codeql: ${{ steps.detect.outputs.should-run-codeql }}"
          echo "Should run trivy: ${{ steps.detect.outputs.should-run-trivy }}"

      - name: Call CodeQL Scan Workflow for JavaScript
        if: steps.detect.outputs.should-run-codeql == 'true'      
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/codeql.yml/dispatches \
            -d '{"ref":"main"}'

      - name: Call CodeQL Scan Workflow for Python
        if: steps.detect.outputs.should-run-trivy == 'true'
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/trivy.yml/dispatches \
            -d '{"ref":"main"}'
