name: Language-Based SATS Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  detect-languages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect Repository Languages
        id: detect
        uses: ./.github/actions/detect-languages
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          languages: 'JavaScript,Python'

  scan:
    runs-on: ubuntu-latest
    needs: detect-languages
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Language Detection Results
        run: |
          echo "JavaScript detected: ${{ needs.detect-languages.outputs.javascript-detected }}"
          echo "Python detected: ${{ needs.detect-languages.outputs..python-detected }}"
          echo "Other languages detected: ${{ needs.detect-languages.outputs.other-detected }}"

      - name: Call CodeQL Scan Workflow for JavaScript
        if: needs.detect-languages.outputs.javascript-detected == 'true'
        uses: ./.github/workflows/codeql.yml

      - name: Call CodeQL Scan Workflow for Python
        if: needs.detect-languages.outputs.python-detected == 'true'
        uses: ./.github/workflows/trivy.yml
       
      - name: Handle Other Languages
        if: needs.detect-languages.outputs.other-detected == 'true'
        run: |
          echo "Other languages detected in the repository. Customize this step to handle them."