name: Language-Based SATS Scan

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read  # Required for checking code and triggering events
  actions: write  # Required for triggering workflows with repository_dispatch

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect Repository Languages
        id: detect
        uses: ./.github/actions/detect-languages
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          languages: 'JavaScript,Python'

      - name: Debug Detected Languages
        run: |
          echo "JavaScript detected: ${{ steps.detect.outputs.javascript-detected }}"
          echo "Python detected: ${{ steps.detect.outputs.python-detected }}"
          echo "Other languages detected: ${{ steps.detect.outputs.other-detected }}"

      - name: Call CodeQL Scan Workflow for JavaScript
        if: steps.detect.outputs.javascript-detected == 'true'
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/codeql.yml/dispatches \
            -d '{"ref":"main"}'

      - name: Call CodeQL Scan Workflow for Python
        if: steps.detect.outputs.python-detected == 'true'
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/trivy.yml/dispatches
       
      - name: Handle Other Languages
        if: steps.detect.outputs.other-detected == 'true'
        run: |
          echo "Other languages detected in the repository. Customize this step to handle them."